### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SilverSoldier** [hackenfreude/docker-eclipse-4.6#1]
Running using `docker run -it --rm hackenfreude/eclipse-4.6` displays error 
```
Eclipse: Cannot open display:
Eclipse:
GTK+ Version Check
Eclipse: Cannot open display: 
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
Eclipse:
An error has occurred. See the log file
/eclipse/configuration/1482211118597.log
```
and exits the docker container.

**Comment by hackenfreude** [comment]
@SilverSoldier your run command (```docker run -it --rm hackenfreude/eclipse-4.6```) is not sufficient because it doesn't set up X forwarding. Please refer to the [readme](https://github.com/hackenfreude/docker-eclipse-4.6#how-to-run-it).

**Comment by hackenfreude** [comment]
@SilverSoldier I am closing this issue. Please let me know if you receive errors after setting up X forwarding.
